apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-registry-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: "NFS 서버 주소"
    path: /nfs/registry
