# basic auth + TLS

apiVersion: apps/v1 
kind: Deployment
metadata:
  name: priv-reg-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: priv-reg-deploy
  template:
    metadata:
      labels: 
        app: priv-reg-deploy
    spec:   
      containers:
      - name: priv-registry
        image: registry:latest
        ports:  
        - containerPort: 5000
        env:    
        - name: REGISTRY_STORAGE_DELETE_ENABLED
          value: "true"
        - name: REGISTRY_AUTH
          value: htpasswd
        - name: REGISTRY_AUTH_HTPASSWD_REALM
          value: "Registry Realm"
        - name: REGISTRY_AUTH_HTPASSWD_PATH
          value: /auth/htpasswd
        - name: REGISTRY_HTTP_TLS_CERTIFICATE
          value: /certs/tls.crt
        - name: REGISTRY_HTTP_TLS_KEY
          value: /certs/tls.key
        volumeMounts:
        - name: auth
          mountPath: /auth
        - name: certs
          mountPath: /certs
      volumes:
      - name: auth
        configMap:
          name: htpasswd
      - name: certs
        secret: 
          secretName: priv-reg-tls
